services:
  tdarr:  
    container_name: tdarr  
    image: ghcr.io/haveagitgat/tdarr:latest  
    restart: unless-stopped  
    network_mode: bridge  
    ports:  
      - 8265:8265 # webUI port  
      - 8266:8266 # server port  
    environment:  
      - TZ=America/New_York  
      - PUID=1000  
      - PGID=1000  
      - UMASK_SET=002  
      - serverIP= # docker host IP
      - serverPort=8266  
      - webUIPort=8265  
      - internalNode=true  
      - inContainer=true  
      - ffmpegVersion=6  
      - nodeName= # docker host hostname  
    volumes:  
      - tdarr_server:/app/server  
      - tdarr_configs:/app/configs  
      - tdarr_logs:/app/logs  
      - /mnt/plex:/media  
      - /transcode_cache:/temp
volumes:
  tdarr_server:
    external: true
  tdarr_configs:
    external: true
  tdarr_logs:
    external: true
