services:
  nc-db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nc-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="Maria123!"
      - MYSQL_PASSWORD="Maria123!"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8008:80
    links:
      - nc-db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/data
    environment:
      - MYSQL_PASSWORD="Maria123!"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nc-db
#      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_TRUSTED_DOMAINS="your.domain.com" # add your docker host IP with the port 8008
volumes:
  nextcloud:
    external: true
  nc-db:
    external: true

#services:
#  nextcloud:
#    image: lscr.io/linuxserver/nextcloud:latest
#    container_name: nextcloud
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/New_York
#    volumes:
#      - nextcloud:/config
#      - /mnt/nextcloud/data:/data
#    ports:
#      - '4443:443'
#    restart: unless-stopped
#volumes:
#  nextcloud:
#    external: true
