## UNTESTED, NEEDS WORK
services:
  nextcloud-db:
    # Attributes
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    pull_policy: always
    # Resources
    volumes:
      - nextcloud-db:/var/lib/mysql
    # Variables
    environment:
      - TZ=America/Detroit
      - MYSQL_DATABASE=${MYSQL_NAME:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Missing MYSQL_PASSWORD in .env file!}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT:?Missing MYSQL_ROOT in .env file!}
    # Interaction
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW

  nextcloud:
    # Attributes
    image: nextcloud
    container_name: nextcloud
    restart: always
    pull_policy: always
    # Network
    ports:
      - 8008:80
    links:
      - nextcloud-db
    # Resources
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/data
    # Variables
    environment:
      - TZ=America/Detroit
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_URL:?Missing NEXTCLOUD_URL in .env file!} # add your docker host IP with the port 8008
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=${MYSQL_NAME:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?Missing MYSQL_PASSWORD in .env file!}

volumes:
  nextcloud:
    driver: local
  nextcloud-db:
    driver: local

#services:
#  nextcloud:
#    # Attributes
#    image: lscr.io/linuxserver/nextcloud:latest
#    container_name: nextcloud
#    restart: unless-stopped
#    # Network
#    ports:
#      - '4443:443'
#    # Resources
#    volumes:
#      - nextcloud:/config
#      - /mnt/nextcloud/data:/data
#    # Variables
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/New_York
#
#volumes:
#  nextcloud:
#    external: true

# ==========================================
# ENVIRONMENT VARIABLES
# =========================================
# MYSQL_ROOT
# MYSQL_PASSWORD
# MYSQL_NAME
# MYSQL_USER
# NEXTCLOUD_URL