services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM= ## get a claim code from https://www.plex.tv/claim/
    volumes:
      - plex:/config
      - /mnt/plex:/data
#    devices:
#      - /dev/dri:/dev/dri
    network_mode: host
    restart: unless-stopped
volumes:
  plex:
    external: true
    