services:
  mariadb-vikunja:
    # Attributes
    image: mariadb:10
    container_name: mariadb-vikunja
    restart: unless-stopped
    pull_policy: always
    # Resources
    volumes:
      - mariadb-vikunja:/var/lib/mysql
    # Variables
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: vikunja-db-user
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: vikunja-db
    # Interaction
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  vikunja:
    # Attributes
    image: vikunja/vikunja
    container_name: vikunja
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - mariadb-vikunja
    # Network
    ports:
      - 3456:3456
    # Resources
    volumes:
      - vikunja:/app/vikunja/files
    # Variables
    environment:
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
      VIKUNJA_DATABASE_HOST: mariadb-vikunja
      VIKUNJA_DATABASE_PASSWORD: dbpass
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja-db-user
      VIKUNJA_DATABASE_DATABASE: vikunja-db

volumes:
  vikunja:
    driver: local
  mariadb-vikunja:
    driver: local
