services:
  dashyIn:
    # Attributes
    image: lissy93/dashy:latest
    container_name: dashy
    restart: always
    pull_policy: always
    # Network
    ports:
      - 8888:8080
    # Resources
    volumes:
      - /app/dashy/conf.yml:/app/user-data/conf.yml
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - NODE_ENV=production
      - preventLocalSave=true
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-} #optional
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-} #optional

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# BASIC_AUTH_USERNAME
# BASIC_AUTH_PASSWORD
