services:
  mealie:
    # Attributes
    image: ghcr.io/mealie-recipes/mealie
    container_name: mealie
    restart: always
    pull_policy: always
    # Network
    ports:
      - 9925:9000
    # Resources
    volumes:
      - mealie:/app/data/
    # Variables
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL= # IP address of host

volumes:
  mealie:
    driver: local