services:
  lubelogger:
    # Attributes
    image: ghcr.io/hargata/lubelogger # Replace with the correct image tag or version
    container_name: lubelogger_container
    restart: always
    pull_policy: always
    depends_on:
      - db
    # Network
    ports:
      - "8911:8080" # Adjust the ports based on the application setup
    # Resources
    volumes:
      - lubeloger_data:/var/lib/lubeloger # Adjust the volume path based on your needs
    # Variables
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_NAME=${DB_NAME?Missing DB_NAME in .env file!}
      - DB_USER=${DB_USER?Missing DB_USER in .env file!}
      - DB_PASSWORD=${DB_PASS?Missing DB_PASS in .env file!}

  db:
    # Attributes
    image: mysql:5.7
    container_name: mysql_lubelogger
    restart: always
    pull_policy: always
    # Network
    ports:
      - "3307:3306"
    # Resources
    volumes:
      - mysql_data:/var/lib/mysql
    # Variables
    environment:
      - MYSQL_DATABASE=${DB_NAME:?Missing DB_NAME in .env file!}
      - MYSQL_USER=${DB_USER:?Missing DB_USER in .env file!}
      - MYSQL_PASSWORD=${DB_PASS:?Missing DB_PASS in .env file!}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT:?Missing DB_ROOT in .env file!}

volumes:
  mysql_data:
    driver: local
  lubeloger_data:
    driver: local

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# DB_NAME
# DB_USER
# DB_PASS
# DB_ROOT

