services:
  lidarr:
    # Attributes
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    pull_policy: always
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - lidarr:/config
      - /mnt/plex/Music:/music
      - /mnt/plex/Downloads:/downloads
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit

volumes:
  host-volume:
    driver: local
