services:
  tunnel:
    # Attributes
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    restart: always
    pull_policy: always
    # Variables
    environment:
      - TZ=America/Detroit
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:?Missing TUNNEL_TOKEN in .env file!}
    # Interaction
    command: tunnel run

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# TUNNEL_TOKEN