services:
  metabase:
    # Attributes
    image: metabase/metabase:latest
    container_name: metabase
    # Network
    hostname: metabase
    networks:
      - metanet1
    ports:
      - 3000:3000
    # Resources
    volumes:
    - /dev/urandom:/dev/random:ro
    # Variables
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    # Interaction
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    # Attributes
    image: postgres:latest
    container_name: postgres
    # Network
    hostname: postgres
    # Resources
    networks:
      - metanet1
    # Variables
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword

networks:
  metanet1:
    driver: bridge
