services:
  gluetun:
    # Attributes
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    pull_policy: always
    # Network
    ports:
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8085:8085 # qbittorrent
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 8191:8191 # FlareSolverr
    # Resources
    volumes:
      - gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    # Variables
    env_file:
      - stack.env
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
#      - OPENVPN_USER=# Find it at account.proton.me/u/0/vpn/OpenVpnIKEv2
#      - OPENVPN_PASSWORD=# Find it at account.proton.me/u/0/vpn/OpenVpnIKEv2
#      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=United States
#      - SERVER_HOSTNAMES=node-us-129.protonvpn.net
      - TZ=America/Detroit
      - UPDATER_PERIOD=24h
    cap_add:
      - NET_ADMIN

  qbittorrent:
    # Attributes
    image: lscr.io/linuxserver/qbittorrent:4.6.5-libtorrentv1
    container_name: qbittorrent
    restart: always
    pull_policy: always
    depends_on:
      - gluetun
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - qbittorrent:/config
      - /mnt/plex/Downloads:/downloads
    # Variables
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - WEBUI_PORT=8085

  prowlarr:
    # Attributes
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    pull_policy: always
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - prowlarr:/config
    # Variables
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit

  sonarr:
    # Attributes
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    pull_policy: always
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - sonarr:/config
      - /mnt/plex/Downloads:/downloads
      - /mnt/plex:/plex
    # Variables
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit

  radarr:
    # Attributes
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    pull_policy: always
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - radarr:/config
      - /mnt/plex/Downloads:/downloads
      - /mnt/plex:/plex
    # Variables
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit

  lidarr:
    # Attributes
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: always
    pull_policy: always
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - lidarr:/config
      - /mnt/plex/Downloads:/downloads
      - /mnt/plex:/plex
    # Variables
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit

  overseerr:
    # Attributes
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: always
    pull_policy: always
    # Network
    ports:
    - 5055:5055
    # Resources
    volumes:
      - overseerr:/app/config
    # Variables
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Detroit

  flaresolverr:
    # Attributes
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: always
    pull_policy: always
    # Network
    network_mode: service:gluetun
    # Resources
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/Detroit

volumes:
  gluetun:
    driver: local
  qbittorrent:
    driver: local
  sonarr:
    driver: local
  radarr:
    driver: local
  lidarr:
    driver: local
  prowlarr:
    driver: local
  overseerr:
    driver: local
