## UNTESTED, NEEDS WORK
services:
  nextcloud-db:
    # Attributes
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    pull_policy: always
    # Resources
    volumes:
      - nextcloud-db:/var/lib/mysql
    # Variables
    environment:
      - MYSQL_ROOT_PASSWORD=MySecretPassword123
      - MYSQL_PASSWORD=MySecretPassword123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=America/Detroit
    # Interaction
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW

  nextcloud:
    # Attributes
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    pull_policy: always
    # Network
    ports:
      - 8008:80
    links:
      - nextcloud-db
    # Resources
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/data
    # Variables
    environment:
      - MYSQL_PASSWORD=MySecretPassword123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_TRUSTED_DOMAINS=your.domain.com # add your docker host IP with the port 8008
      - TZ=America/Detroit

volumes:
  nextcloud:
    driver: local
  nextcloud-db:
    driver: local

#services:
#  nextcloud:
#    # Attributes
#    image: lscr.io/linuxserver/nextcloud:latest
#    container_name: nextcloud
#    restart: unless-stopped
#    # Network
#    ports:
#      - '4443:443'
#    # Resources
#    volumes:
#      - nextcloud:/config
#      - /mnt/nextcloud/data:/data
#    # Variables
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/New_York
#
#volumes:
#  nextcloud:
#    external: true
