services:
  metabase:
    # Attributes
    image: metabase/metabase
    container_name: metabase
    restart: always
    pull_policy: always
    # Network
    hostname: metabase
    networks:
      - metanet1
    ports:
      - 3000:3000
    # Resources
    volumes:
    - /dev/urandom:/dev/random:ro
    # Variables
    environment:
      - TZ=America/Detroit
      - MB_DB_TYPE=postgres
      - MB_DB_PORT=5432
      - MB_DB_HOST=postgres
      - MB_DB_DBNAME=${DB_NAME:?Missing DB_NAME in .env file!}
      - MB_DB_USER=${DB_USER:?Missing DB_USER in .env file!}
      - MB_DB_PASS=${DB_PASS:?Missing DB_PASS in .env file!}
    # Interaction
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    # Attributes
    image: postgres
    container_name: postgres
    restart: always
    pull_policy: always
    # Network
    hostname: postgres
    # Resources
    networks:
      - metanet1
    # Variables
    environment:
      - TZ=America/Detroit
      - POSTGRES_DB=${DB_NAME:?Missing DB_NAME in .env file!}
      - POSTGRES_USER=${DB_USER:?Missing DB_USER in .env file!}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Missing DB_PASSWORD in .env file!}

networks:
  metanet1:
    driver: bridge

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# DB_NAME
# DB_USER
# DB_PASS
# DB_ROOT
