services:  
  panel:
    # Attributes
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    pull_policy: always
    # Network
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    # Resources
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/app/storage/logs"
    # Variables
    environment:
      APP_URL: "https://${DOMAIN_URL:?Missing DOMAIN_URL in .env file!}"
      APP_TIMEZONE: "America/Detroit"
      DB_PASSWORD: ${DB_PASS:?Missing DB_PASS in .env file!}
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

  database:
    # Attributes
    image: mariadb:10.5
    restart: always
    pull_policy: always
    # Resources
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    # Variables
    environment:
      MYSQL_PASSWORD: ${DB_PASS:?Missing DB_PASS in .env file!}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT:?Missing DB_ROOT in .env file!}
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    # Interaction
    command: --default-authentication-plugin=mysql_native_password

  cache:
    # Attributes
    image: redis:alpine
    restart: always
    pull_policy: always

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# DB_PASS
# DB_ROOT
# DOMAIN_URL