services:
  gluetun:
    # Attributes
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    # Network
    ports:
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 8085:8085 # qbittorrent
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 6767:6767 # Bazarr
      - 8191:8191 # FlareSolverr
    # Resources
    volumes:
      - gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    # Variables
    env_file:
      - stack.env
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
#      - OPENVPN_USER=# Find it at account.proton.me/u/0/vpn/OpenVpnIKEv2
#      - OPENVPN_PASSWORD=# Find it at account.proton.me/u/0/vpn/OpenVpnIKEv2
      - SERVER_COUNTRIES=United States
      - TZ=America/New_York
      - UPDATER_PERIOD=24h
    cap_add:
      - NET_ADMIN

  qbittorrent:
    # Attributes
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      - gluetun
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - qbittorrent:/config
      - /mnt/plex/Downloads:/downloads
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8085

  prowlarr:
    # Attributes
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - prowlarr:/config
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

  sonarr:
    # Attributes
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - sonarr:/config
      - /mnt/plex/Shows:/shows
      - /mnt/plex/Downloads:/downloads
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

  radarr:
    # Attributes
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - radarr:/config
      - /mnt/plex/Movies:/movies
      - /mnt/plex/Downloads:/downloads
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

  lidarr:
    # Attributes
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - lidarr:/config
      - /mnt/plex/Music:/music
      - /mnt/plex/Downloads:/downloads
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

  overseerr:
    # Attributes
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    # Network
    ports:
    - 5055:5055
    # Resources
    volumes:
      - overseerr:/app/config
    # Variables
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York

  flaresolverr:
    # Attributes
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    # Network
    network_mode: service:gluetun
    # Resources
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York

volumes:
  gluetun:
    external: true
  qbittorrent:
    external: true
  sonarr:
    external: true
  radarr:
    external: true
  lidarr:
    external: true
  prowlarr:
    external: true
  overseerr:
    external: true
