services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger # Replace with the correct image tag or version
    container_name: lubelogger_container
    ports:
      - "8911:8080" # Adjust the ports based on the application setup
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=lubeloger_user
      - DB_PASSWORD=secret_password
      - DB_NAME=lubeloger_db
    volumes:
      - ./data:/var/lib/lubeloger # Adjust the volume path based on your needs
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_lubelogger
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lubeloger_db
      MYSQL_USER: lubeloger_user
      MYSQL_PASSWORD: secret_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
    driver: local
  data:
    driver: local
