services:
  dashy:
    # Attributes
    image: lissy93/dashy
    container_name: dashy
    restart: unless-stopped
    pull_policy: always
    # Network
    ports:
      - 8888:8080
    # Resources
    volumes:
      - /app/dashy/conf.yml:/app/user-data/conf.yml
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - NODE_ENV=production
