services:
  dashy:
    # Attributes
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    # Network
    ports:
      - '8888:8080'
    # Resources
    volumes:
      - /home/$USER/dashy/dashy-conf.yml:/app/user-data/conf.yml
    # Variables
	  environment:
      - PUID=1000
      - PGID=1000
      - NODE_ENV=production
