services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger # Replace with the correct image tag or version
    container_name: lubelogger
    ports:
      - "8911:8080" # Adjust the ports based on the application setup
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=lubeloger_user # Change me
      - DB_PASSWORD=secret_password # Change me
      - DB_NAME=lubeloger_db
    volumes:
      - lube_logger:/data # Adjust the volume path based on your needs
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lubelogger_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Change me
      MYSQL_DATABASE: lubeloger_db
      MYSQL_USER: lubeloger_user # Change me
      MYSQL_PASSWORD: secret_password # Change me
    volumes:
      - lube_mysql_data:/data
    ports:
      - "3307:3306"

volumes:
  lube_mysql_data:
    driver: local
  lube_logger:
    driver: local
