services:
  pihole:
    # Attributes
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    pull_policy: always
    # Network
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    # Resources
    volumes:
      - pihole:/etc/pihole
      - dnsmasq.d:/etc/dnsmasq.d
    # Variables
    env_file:
      - stack.env
    environment:
      - TZ=America/Detroit
#      - WEBPASSWORD='set a secure password here or it will be random'

volumes:
  pihole:
    driver: local
  dnsmasq.d:
    driver: local
