services:
  uptime-kuma:
    # Attributes
    image: louislam/uptime-kuma
    container_name: kuma
    restart: always
    pull_policy: always
    # Network
    ports:
      - 3001:3001
    # Resources
    volumes:
      - kuma:/app/data
    # Variables
    environment:
      - TZ=America/Detroit

volumes:
  kuma:
    driver: local
