services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - heimdall:/config
    ports:
      - '8088:80'
      - '4433:443'
    restart: unless-stopped
volumes:
  heimdall:
    external: true
    