services:
  bazarr:
    # Attributes
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    # Network
    network_mode: service:gluetun
    # Resources
    volumes:
      - bazarr:/config
      - /mnt/plex/Movies:/movies
      - /mnt/plex/Shows:/shows
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York

volumes:
  bazarr:
    external: true
