services:
  mariadb:
    # Attributes
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    restart: always
    pull_policy: always
    # Network
    ports:
      - 3306:3306
    # Resources
    volumes:
      - mariadb-data:/config
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=${DB_NAME:?Missing DB_NAME in .env file!} #optional
      - MARIADB_USER=${DB_USER:?Missing DB_USER in .env file!} #optional
      - MARIADB_PASSWORD=${DB_PASS:?Missing DB_PASS in .env file!} #optional
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional

volumes:
   mariadb-data:
    driver: local

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# DB_NAME
# DB_USER
# DB_PASS
