services:
  mealie:
    # Attributes
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    # Network
    ports:
        - "9925:9000"
    # Resources
    volumes:
      - mealie-data:/app/data/
#    deploy:
#      resources:
#        limits:
#          memory: 2000M
    # Variables
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL= # IP address of host

volumes:
  mealie-data:
    driver: local
