services:
  uptimekuma:
    # Attributes
    image: louislam/uptime-kuma
    container_name: uptimekuma
    restart: always
    pull_policy: always
    # Network
    ports:
      - 3001:3001
    # Resources
    volumes:
      - uptimekuma:/app/data/
    # Variables
    environment:
    - TZ=America/Detroit
volumes:
  uptimekuma:
    driver: local