services:
  ollama:
    # Attributes
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    # Resources
    volumes:
      - ollama:/root/.ollama
    deploy: # Add this deploy to enable GPU acceleration
      resources:
        reservations:
          devices:
            #- driver: nvidia
              count: all
              capabilities: [gpu]
    # Interaction
    tty: true

  open-webui:
    # Attributes
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    restart: unless-stopped
    # Network
    ports:
      - 3030:8080
    # Resources
    volumes:
      - open-webui:/app/backend/data
    # Variables
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  ollama:
    external: true
  open-webui:
    external: true
