services:
  vaultwarden:
    # Attributes
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    # Network
    ports:
      - 11111:80
    # Resources
    volumes:
      - vw-data:/data
    # Variables
    environment:
      DOMAIN: ${DOMAIN_URL:?Missing DOMAIN_URL in .env file!}
      SIGNUPS_ALLOWED: "true" # Remember to disable signup after setup

volumes:
  vw-data:
    driver: local

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# DOMAIN_URL
