services:
  homebox:
    # Attributes
    image: ghcr.io/hay-kot/homebox # latest-rootless (optional)
    container_name: homebox
    restart: always
    pull_policy: always
    # Network
    ports:
      - 3100:7745
    # Resources
    volumes:
      - homebox-data:/data/
    # Variables
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=100
      - HBOX_OPTIONS_ALLOW_REGISTRATION=false
      - HBOX_TZ=America/Detroit
      - ENV_TZ=America/Detroit

volumes:
   homebox-data:
    driver: local
