services:
  heimdall:
    # Attributes
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    pull_policy: always
    # Network
    ports:
      - 8088:80
      - 4433:443
    # Resources
    volumes:
      - heimdall:/config
    # Variables
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit

volumes:
  heimdall:
    driver: local
