services:
  uptime-kuma:
    # Attributes
    image: louislam/uptime-kuma
    container_name: kuma
    restart: always
    # Network
    ports:
      - '3001:3001'
    # Resources
    volumes:
      - kuma:/app/data

volumes:
  kuma:
    external: true
