services:
  caddy:
    # Attributes
    image: docker.io/library/caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    pull_policy: always
    # Network
    network_mode: host
    # Resources
    volumes:
      - /etc/docker/searxng-docker/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    # Variables
    env_file:
      - stack.env
    environment:
      - SEARXNG_HOSTNAME=http://127.0.0.1:8844
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
      - TZ=America/Detroit
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    # Interaction
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1

  redis:
    # Attributes
    image: docker.io/valkey/valkey:7-alpine
    container_name: redis
    restart: unless-stopped
    pull_policy: always
    # Network
    networks:
      - searxng
    # Resources
    volumes:
      - valkey-data:/data
    # Variables
    environment:
      - TZ=America/Detroit
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    # Interaction
    command: valkey-server --save 30 1 --loglevel warning
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1

  searxng:
    # Attributes
    image: docker.io/searxng/searxng
    container_name: searxng
    restart: unless-stopped
    pull_policy: always
    # Network
    networks:
      - searxng
    ports:
      - 8844:8080
    # Resources
    volumes:
      - /etc/docker/searxng-docker/searxng:/etc/searxng:rw
    # Variables
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-127.0.0.1}/
      - TZ=America/Detroit
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    # Interaction
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1

networks:
  searxng:

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local
  valkey-data:
    driver: local
