services:
  pihole:
    # Attributes
    image: pihole/pihole
    container_name: pihole
    restart: always
    pull_policy: always
    # Network
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    # Resources
    volumes:
      - pihole:/etc/pihole
      - dnsmasq.d:/etc/dnsmasq.d
    # Variables
    env_file:
      - stack.env
    environment:
      - TZ=America/Detroit
      - WEBPASSWORD=${WEBPASSWORD:?Missing WEBPASSWORD in .env file!}

volumes:
  pihole:
    driver: local
  dnsmasq.d:
    driver: local

# ==========================================
# ENVIRONMENT VARIABLES
# ==========================================
# WEBPASSWORD
