services:
  tunnel:
    # Attributes
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    restart: unless-stopped
    # Variables
    env_file:
      - stack.env
#    environment:
#      - TUNNEL_TOKEN= # mytokenfromcloudflare-com
    # Interaction
    command: tunnel run
